In [0]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import kurtosis, skew, pearsonr, spearmanr
import seaborn as se
%matplotlib inline

# Question 1

In [0]:
#Loading stock datas
Stock_1=pd.read_csv('Stock_1.csv')
Stock_2=pd.read_csv('Stock_2.csv')

In [0]:
#Showing stock_1 data with its log_return
Stock_1.head(3)

         Date  Year  Adj Close  log_return
0  2016-01-04  2016  23.916285   -0.003499
1  2016-01-05  2016  23.807615   -0.004554
2  2016-01-06  2016  23.554054   -0.010708

In [0]:
#Showing stock_2 data with its log_return
Stock_2.head(3)

         Date  Year  Adj Close  log_return
0  2016-01-04  2016  99.925850   -0.003448
1  2016-01-05  2016  97.421768   -0.025379
2  2016-01-06  2016  95.515244   -0.019764

In [0]:
#Computing Statistics
Mean_stock_1=np.mean(Stock_1.log_return)
print("Mean_stock_1:%f" %Mean_stock_1)

Mean_stock_2=np.mean(Stock_2.log_return)
print("Mean_stock_2:%f" %Mean_stock_2)


Stand_Dev_stock_1=np.std(Stock_1.log_return)
print("Stand_Dev_stock_1:%f" %Stand_Dev_stock_1)

Stand_Dev_stock_2=np.std(Stock_2.log_return)
print("Stand_Dev_stock_2:%f" %Stand_Dev_stock_2)



Skewness_stock_1=skew(Stock_1.log_return)
print("Skewness_stock_1:%f" %Skewness_stock_1)

Skewness_stock_2=skew(Stock_2.log_return)
print("Skewness_stock_2:%f" %Skewness_stock_2)



Kurtosis_stock_1=kurtosis(Stock_1.log_return)
print("Kurtosis_stock_1:%f" %Kurtosis_stock_1)

Kurtosis_stock_2=kurtosis(Stock_2.log_return)
print("Kurtosis_stock_2:%f" %Kurtosis_stock_2)

Mean_stock_1:0.000854
Mean_stock_2:0.001011
Stand_Dev_stock_1:0.011818
Stand_Dev_stock_2:0.013004
Skewness_stock_1:-0.007233
Skewness_stock_2:-0.123234
Kurtosis_stock_1:11.938240
Kurtosis_stock_2:5.006656

In [0]:
#Calculating covariance
covar=np.cov(Stock_1.log_return,Stock_2.log_return)
print(covar)

[[1.39932721e-04 5.08150555e-05]
 [5.08150555e-05 1.69452010e-04]]

In [0]:
#Calculating correlation
correl=pearsonr(Stock_1.log_return,Stock_2.log_return)
print("Pearsons correlation:%f" %correl[0])


correla=spearmanr(Stock_1.log_return,Stock_2.log_return)
print("Spaermans correlation:%f" %correla[0])

Pearsons correlation:0.329997
Spaermans correlation:0.382580

#Correlation Vs Covariance

Correlation and Covariance are very significant terms in the field of Staticstics. These two terms both measure the relationship and the dependency between two variables. The question is "What set them apart"?

Covariance indicates the direction of the linear relationship between variabbles while Correlation measure the strength and direction of the linear relationship. Hence Correlation values are standardized while that of Covariance are not.

# Question 2

In [0]:
Stock_1=Stock_1.drop(['Year'], axis=1)
Stock_2=Stock_2.drop(['Year'], axis=1)

In [0]:
#merging the two stock data and dividing into two uneven parts

Stock_1.rename(columns={'Adj Close':'Adj Close_1',
                          'log_return':'log_return_1'}, 
                 inplace=True)
Stock_2.rename(columns={'Adj Close':'Adj Close_2',
                          'log_return':'log_return_2'}, 
                 inplace=True)

All=pd.merge(Stock_1,Stock_2, how='inner', on='Date')
All.head(3)

         Date  Adj Close_1  log_return_1  Adj Close_2  log_return_2
0  2016-01-04    23.916285     -0.003499    99.925850     -0.003448
1  2016-01-05    23.807615     -0.004554    97.421768     -0.025379
2  2016-01-06    23.554054     -0.010708    95.515244     -0.019764

In [0]:
from sklearn.model_selection import train_test_split

## Spliting data into  80% and 20% 
Big_All, Small_All = train_test_split( All, test_size=0.20, random_state=42)

In [0]:
Big_All.head(3)

           Date  Adj Close_1  log_return_1  Adj Close_2  log_return_2
423  2017-09-07    30.324333     -0.003458   158.305695     -0.004023
19   2016-02-01    21.262947     -0.013116    91.465096     -0.009393
323  2017-04-17    30.847710      0.005844   138.116943      0.005515

In [0]:
Small_All.head(3)

           Date  Adj Close_1  log_return_1  Adj Close_2  log_return_2
268  2017-01-26    28.827639      0.001302   118.235039      0.000492
73   2016-04-19    25.889612      0.004954   101.955765     -0.005318
289  2017-02-27    32.128654     -0.001750   133.345215      0.001974