In [0]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as se
%matplotlib inline

In [0]:
train=pd.read_csv('Train.csv')
test=pd.read_csv('Test.csv')
test.head()

         Order No       User Id  ... Destination Long      Rider Id
0  Order_No_19248  User_Id_3355  ...        36.822390  Rider_Id_192
1  Order_No_12736  User_Id_3647  ...        36.823907  Rider_Id_868
2    Order_No_768  User_Id_2154  ...        36.851365   Rider_Id_26
3  Order_No_15332  User_Id_2910  ...        36.790658  Rider_Id_685
4  Order_No_21373  User_Id_1205  ...        36.792161  Rider_Id_858

[5 rows x 25 columns]